#!/bin/bash

# Prevent unintentional commits to master
current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

if [[ $current_branch == "master" ]]
then
    read -p "Really commit to master? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        echo "Alright, if you say so..."
        exit 0
    fi
    echo "Good call, aborting."
    exit 1
else
    exit 0
fi
